### PR TITLE
Add reference to libusb FAQ

### LINKED ISSUE #182: Add Troubleshooting FAQ
### Runtime errors
* LIBUSB_ERROR_BUSY
  * Linux: detach_kernel_driver (Example in #174)
* LIBUSB_ERROR_ACCESS
  * macOS: Can't open devices that have a kernel driver, no good workaround. (discussion on #30)
     * Usually comes up with HID devices -- is there a recommended libhid library?
  * Linux: permissions, udev rules
* LIBUSB_ERROR_NOT_SUPPORTED
  * Windows: Bind WinUSB driver with libwdi / Zadig
    * Mention WCID for custom devices
* LIBUSB_ERROR_NO_DEVICE
   * macOS doesn't configure devices with bDeviceClass=255 "vendor defined" (#61)
     * If it's your firmware, use bDeviceClass=0 "defined at interface level" instead
     * workaround is `.open(false)`, `.setConfiguration(1)` to tell the kernel to configure the device.

### Install errors
* Install fails with `gyp WARN EACCES user "root" does not have permission to access the dev dir` (#175, #210, #218)
   * Don't run npm as root. Best way is to install node via nvm, which sets up permissions correctly to run `npm -g` as your normal user.
   * Or if you really have to, `npm install --unsafe-perm usb`.
   * Common issue for all NPM packages with native code nodejs/node-gyp#454 (comment)

### PR DESCRIPTION
**Pull request by thegecko**
## Changes

- Add reference to libusb FAQ, covering the majority of troubleshooting issues

## Fixes

Fixes #182 

## Checklist

Have you...

- [ ] Tested the change acts as expected
- [ ] Checked the change doesn't remove or change existing functionality
- [ ] Considered how the feature impacts the product and tested around it (not just the happy paths)
- [ ] Where possible, executed the hardware tests on multiple operating systems

### CODE REVIEW

**Review by mildsunrise — APPROVED** [review]
Just a suggestion, but maybe we could move that link up into the "prerrequisites" section? I say this because we already say some troubleshooting-like stuff there, such as

> if you get LIBUSB_ERROR_NOT_SUPPORTED when attempting to open your device, it's possible your device doesn't have a WinUSB driver for libusb to use

so it may be a better / more visible place. Also now that I think of it, at the end of the "Windows" subsection maybe we could also say something like:

> For further info, check [How to use libusb on Windows](https://github.com/libusb/libusb/wiki/Windows#user-content-How_to_use_libusb_on_Windows) in the libusb's wiki.

**Comment by mcuee** [comment]
If you have some comments or improvement ideas for libusb FAQ, you are welcome to comment here.
* https://github.com/libusb/libusb/issues/1253

**Comment by thegecko** [comment]
Is that better @mildsunrise ?

**Review by mildsunrise — APPROVED** [review]
yes, thank you :)

**Pull request merged**
