### PR TITLE
Update device.cc

### PR DESCRIPTION
**Pull request by cleoo**
Avoid node js fatal exception

## Changes
Send exception back to node

## Fixes
fix "Abandon (core dumped)" in certain conditions, including unexpected disappearances of devices from the usb bus. The errors are traced back to node, which makes these errors catchable

## Checklist

- [x] Tested the change acts as expected
- [x] Checked the change doesn't remove or change existing functionality
- [ ] Considered how the feature impacts the product and tested around it (not just the happy paths)
- [ ] Where possible, executed the hardware tests on multiple operating systems

### CODE REVIEW

**Comment by cleoo** [comment]
The error messages returned have little to do with my pull request.

**Comment by cleoo** [comment]
Hi, could I have an idea of ​​the integration time of these changes? I just tested this morning on a sample of machines and all my errors now go through process.on('uncaugthException'), it is an open door to correct processing of these exceptions that were previously invisible. I ask the question of the time because I have about 800 machines to update

**Comment by thegecko** [comment]
Merges are blocked on this being fixed:

https://github.com/prebuild/prebuildify-cross/issues/20

We need prebuilds to pass before merging and releasing.

**Comment by thegecko** [comment]
@cleoo can you merge your PRs into one, please and add a descriptive title.

**Pull request closed without merging**
