### PR TITLE
Fix initial windows device list

### LINKED ISSUE #529: Initial detaching of a device doesn't trigger detach event.
## Bug Description:

Starting the app with the device plugged in, then physically unplugging it doesn't trigger `usb.on('detach', (device) => {`. If I unplug, then plug, then unplug the device again, then my detach event finally fires. Also, if I start the app with the device unplugged, it works on the first detach. 

It seems like a detach event can't happen before an attach event, or something. I noticed that a bunch of attach events are fired when *detaching* initially. But none have my device id, so I don't know what's going on. Please advise. Thank you.

## Steps to Reproduce:
1. Plug in your device
2. Detach it (only attach events are fired)
3. Plug it back in (attach event is fired with that device id)
4. Detach it again, this time you will see that device id being detached.

## Additional Information
- Operating System: Windows 10 64 bit.
- Runtime node v16.16.0
- Node USB Version (`npm ls usb`): 2.5.0

### PR DESCRIPTION
**Pull request by thegecko**
## Changes

- Set initial device list for windows polling

## Fixes

- Fixes #529

## Checklist

Have you...

- [x] Tested the change acts as expected
- [x] Checked the change doesn't remove or change existing functionality
- [x] Considered how the feature impacts the product and tested around it (not just the happy paths)
- [x] Where possible, executed the hardware tests on multiple operating systems

cc @mildsunrise  @Newbrict @Julusian

### CODE REVIEW

**Comment by Newbrict** [comment]
I will try to figure out how to pull this into my package.json, and if I'm able to, I'll test it. Haha.

**Comment by Newbrict** [comment]
> I will try to figure out how to pull this into my package.json, and if I'm able to, I'll test it. Haha.

Any tips appreciated. I'm still lost.

**Comment by thegecko** [comment]
Clone it recursively, switch branches, yarn and yarn link

**Comment by Newbrict** [comment]
Sorry for the delay, I've been working on something else, but I will get back to this ASAP.

**Comment by thegecko** [comment]
Refactored the code in this area for readability and confirmed this fixes initial device listing on Windows

**Pull request merged**
