### PR TITLE
Patches WebUSBDevice to force reconfiguration deviceClass 0xff

### PR DESCRIPTION
**Pull request by jounii**
## Changes

Tries to detect if deviceClass 0xff devices have not been configured by default (macOS) and then uses the workaround to set configuration manually.

Tested with Sony MDS-JB980 hardware through netmd-js library using node-usb WebUSB on macOS.

## Fixes
- #61 - So that it works for WebUSB without hacks prior using WebUSB

## Checklist

- [X] Tested the change acts as expected
- [X] Checked the change doesn't remove or change existing functionality
- [x] Considered how the feature impacts the product and tested around it (not just the happy paths)
- [ ] Where possible, executed the hardware tests on multiple operating systems

### CODE REVIEW

**Comment by thegecko** [comment]
Sorry this has been a bit quiet, I'm trying to decide what to do.

Concerns:
- The forced reopen doesn't feel right
- However, neither does exposing the `open(false)` functionality through webusb
- you can't check for interfaces without it being opened initially
- `setConfiguration` is already exposed on the webusb class

Would this be a better approach?

```typescript
            if (!this.opened) {
                // Don't read config descriptor of vendor-specific devices on macos
                // https://github.com/node-usb/node-usb/issues/61
                if (this.deviceClass === 0xff && platform() === 'darwin') {
                    this.device.open(false);
                } else {
                    this.device.open();
                }
            }
```

And then call `selectConfiguration` on webusb later? Or does that still fall over due to needing `device.configDescriptor` @jounii ?

**Comment by jounii** [comment]
> Concerns:
> 
> * The forced reopen doesn't feel right
> * However, neither does exposing the `open(false)` functionality through webusb

Yes I wasn't happy about it either, but couldn't figure any other way besides having non-standard callback exposed. A bit like the `devicesFound`, but for `beforeOpen` or `afterOpen` or maybe `configureDevice` for doing manually the re-open.. Or maybe just a flag to allow "forced reopen" or so. The `platform()` check sounds good to limit to macOS. The existing `devicesFound` comes too late as it expects the device being opened successfully and listed.

> * you can't check for interfaces without it being opened initially
> * `setConfiguration` is already exposed on the webusb class
> 
> And then call `selectConfiguration` on webusb later? Or does that still fall over due to needing `device.configDescriptor` @jounii ?

I will test, but I recall it did not find the device unless the interfaces array was initilized and without the setConfiguration the device was basically considered non-existing as interfaces was empty array and thus considered "opened", yet not really opened.

**Comment by thegecko** [comment]
I've reimplemented your fix in https://github.com/node-usb/node-usb/pull/739 , which i think is a little neater.

I'm not able to test this, but can't see why it wouldn't work and fix the issue. Feedback is helpful though!

**Comment by jounii** [comment]
> I've reimplemented your fix in #739 , which i think is a little neater.
> 
> I'm not able to test this, but can't see why it wouldn't work and fix the issue. Feedback is helpful though!

Looks great and neat solution. I will test. I have been occupied with other things and didn't yet get back to this.

**Comment by thegecko** [comment]
Closing this in favour of #739

**Pull request closed without merging**
